[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter']
hook_source = '''
  let s:ddc_sourceOptions = {}
  let s:ddc_sourceOptions['_'] = #{
      \   matchers: ['matcher_fuzzy'],
      \   converters: ['converter_fuzzy'],
      \   ignoreCase: v:true,
      \ }
  let s:ddc_sourceOptions['around'] = #{
      \   mark: 'A',
      \   maxKeywordLength: 30,
      \ }
  let s:ddc_sourceOptions['buffer'] = #{
      \   mark: 'B',
      \   maxKeywordLength: 30,
      \ }
  let s:ddc_sourceOptions['file'] = #{
      \   mark: 'F',
      \   isVolatile: v:true,
      \   mode: 'win32',
      \ }
  " https://github.com/kuuote/dotvim/blob/7fbd83a2aedb1e30405f9bd1d8126b04dc5fe72e/conf/vim-lsp.toml#L50
  " メソッド呼び出しを補完
  let s:ddc_sourceOptions['vim-lsp'] = #{
      \   mark: 'L',
      \   forceCompletionPattern: '\..?',
      \   minAutoCompleteLength: 2,
      \ }
  let s:ddc_sourceOptions['vsnip'] = #{
      \   mark: 'S',
      \   dup: v:true,
      \ }

  call ddc#custom#patch_global('sourceOptions', s:ddc_sourceOptions)

  call ddc#custom#patch_filetype(
      \ ['rst'], 'sources', ['buffer', 'around', 'file', 'vsnip'])
  call ddc#custom#patch_filetype(
      \ ['go', 'python', 'typescript'], 'sources', ['vim-lsp', 'file', 'vsnip'])
  call ddc#custom#patch_filetype(
      \ ['autohotkey', 'cfg', 'git', 'javascript', 'markdown', 'plantuml', 'snippet', 'vb', 'xsl'], 'sources', ['buffer', 'around', 'file'])


  " ddc.vim を使用しない filetype では <Tab>
  " popupで候補が選択されている場合、vsnipの展開ができるなら展開、できないなら次の候補へ
  " popupが表示されている場合、次の候補へ
  " vsnipのジャンプができる場合、次のジャンプ位置へ
  " 空白行の場合、<Tab> そうでなければ補完
  imap <silent><expr> <Tab>
        \ !has_key(ddc#custom#get_filetype(), &filetype) ? '<Tab>' :
        \ pum#entered() ? vsnip#expandable()  ? '<Plug>(vsnip-expand)' : '<Cmd>call pum#map#insert_relative(+1)<CR>' :
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
        \ vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' :
        \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ? '<Tab>' :
        \ ddc#map#manual_complete()
  smap <silent><expr> <Tab>
        \ vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' :
        \ '<Tab>'
  imap <silent><expr> <C-j>
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
        \ '<C-j>'
  " smap <silent><expr> <C-n>
  "      \ vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' :
  "      \ '<C-n>'
  " pum 表示時の imap <C-n> が意図したとおりに動かないのでコメントアウト。
  " imap <C-n> と <C-j> を同じマッピングにしても動きが違う？　Vim のバグ？
  " imap <silent><expr> <C-n>
  "      \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
  "      \ '<Cmd>normal! gj<CR>'
  imap <silent><expr> <S-Tab>
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' :
        \ vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' :
        \ '<C-h>'
  smap <silent><expr> <S-Tab>
        \ vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' :
        \ '<S-Tab>'
  imap <silent><expr> <C-k>
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' :
        \ '<Cmd>normal! D<CR>'
  " <C-n> をコメントアウトしたのでこちらもセットで。
  " imap <silent><expr> <C-p>
  "      \ pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' :
  "      \ '<Cmd>normal! gk<CR>'

  " Shougo/pum.vim
  call ddc#custom#patch_global('ui', 'pum')
  call ddc#custom#patch_global('backspaceCompletion', v:true)
  " tani/ddc-fuzzy
  call ddc#custom#patch_global('postFilters', ['sorter_fuzzy'])
  call ddc#custom#patch_global('filterParams', #{
    \   converter_fuzzy: #{
    \     hlGroup: 'SpellBad'
    \   }
    \ })

  " For thinca/partedit
  autocmd OptionSet buftype if &buftype ==# 'acwrite' | call s:forPartedit() | endif
  function! s:forPartedit() abort
    call ddc#custom#patch_buffer('specialBufferCompletion', v:true)
    nnoremap <buffer> qq <Cmd>ParteditEnd<CR>
  endfunction

  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = '''
  call pum#set_option('use_complete', v:true)
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

# [[plugins]]
# repo = 'matsui54/ddc-matcher_fuzzy'
# on_source = 'ddc.vim'

# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# on_source = 'ddc.vim'

# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
depends = 'ddc.vim'
on_ft = ['toml', 'vim']
hook_source = '''
  call ddc#custom#patch_global('sourceOptions', #{necovim: #{mark: 'V'}})
  call ddc#custom#patch_filetype(['vim', 'toml'], 'sources', ['necovim', 'buffer', 'around', 'file', 'vsnip'])
'''

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
# rev = '8698aa'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
# rev = '257293'
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
lazy = 1
hook_add = '''
  let g:vsnip_snippet_dir = expand('~/vimfiles/rc/vsnip')
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = 'vim-vsnip'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
# rev = 'b8f62b'
depends = 'denops.vim'
on_source = 'ddc.vim'
hook_source = '''
  call popup_preview#enable()
'''

# [[plugins]]
# repo = 'hokorobi/neco-syntax'
# on_source = 'ddc.vim'

