[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'sourceOptions': {
    \     '_': {
    \       'ignoreCase': v:true,
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'sources': [{'name': 'file_rec', 'params': {}}],
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \       'autoResize': v:false,
    \       'reversed': v:false,
    \       'split': 'no',
    \     }
    \   },
    \ })
'''
[plugins.ftplugin]
ddu-ff = '''
inoremap <buffer><silent><nowait> <Esc> <Esc><Cmd>close<CR>

nnoremap <buffer><silent>         <CR>  <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent><nowait> q     <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent>         <CR>  <Esc><Cmd>close<CR><Cmd>call ddu#ui#ff#do_action('itemAction')<CR>

nnoremap <buffer><silent><nowait> <CR>  <Cmd>close<CR>
nnoremap <buffer><silent><nowait> <Esc> <Cmd>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
