[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'sourceOptions': {
    \     '_': {
    \       'ignoreCase': v:true,
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'sources': [{'name': 'file_rec', 'params': {}}, {'name': 'mr'}, {'name': 'register'}, {'name': 'buffer'}],
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \       'autoResize': v:false,
    \       'reversed': v:true,
    \       'split': 'horizontal',
    \       'winHeight': '5',
    \     }
    \   },
    \ })
'''
[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent>         <CR>  <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent><nowait> q     <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent>         <CR>  <Cmd>call ddu#ui#ff#close()<CR><Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
" FIXME: ESC ですべて閉じたい
inoremap <buffer><silent><nowait> <Esc> <Cmd>call ddu#ui#ff#do_action('quit')<CR>

nnoremap <buffer><silent><nowait> <CR>  <Cmd>call ddu#ui#ff#close()<CR>
nnoremap <buffer><silent><nowait> <Esc> <Cmd>call ddu#ui#ff#close()<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'
hook_add = '''
  nnoremap <silent> <Space>du <Cmd>Ddu mr<CR>
  nnoremap <silent> <Space>db <Cmd>Ddu buffer<CR>
  nnoremap <silent> <Space>dr <Cmd>Ddu register<CR>
  nnoremap <silent> <Space>df <Cmd>Ddu file_rec<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
