[[plugins]]
repo = 'Shougo/dein.vim'
# https://github.com/Shougo/dein.vim/pull/515 で CtrlPのhooks_file が読み込めなくなってしまったみたい
rev = 'a3515eb'

[[multiple_plugins]]
plugins = ['ddu.vim', 'dein.vim']
hook_add = '''
call ddu#custom#patch_global(#{
    \   sourceOptions: #{
    \     dein: #{
    \       defaultAction: ['update'],
    \     },
    \   },
    \ })
nnoremap <silent> <Space>du <Cmd>call ddu#start(#{sources: [#{name: 'dein'}]})<CR>
'''
