[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = 'denops.vim'
on_func = 'signature_help#'
hooks_file = '~/vimfiles/plug/conf/denops-signature_help.vim'

[[plugins]]
repo = 'ompugao/ctrlp-kensaku'
depends = ['denops.vim', 'vim-kensaku']
on_cmd = ['CtrlPKensaku', 'ToggleCtrlPKensaku']
hooks_file = '~/vimfiles/plug/conf/ctrlp-kensaku.vim'

[[plugins]]
repo = 'lambdalisue/vim-kensaku'
depends = 'denops.vim'
lazy = true

[[plugins]]
repo = 'lambdalisue/vim-gin'
on_cmd = [
  'Gin',
  'GinBranch',
  'GinBrowse',
  'GinBuffer',
  'GinChaperon',
  'GinDiff',
  'GinEdit',
  'GinLog',
  'GinPatch',
  'GinStatus',
]
depends = 'denops.vim'
hooks_file = '~/vimfiles/plug/conf/gin.vim'

[[plugins]]
repo = 'Milly/hey.vim'
rev = 'buffering'
depends = 'denops.vim'
on_cmd = 'Hey'
hooks_file = '~/vimfiles/plug/conf/hey.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
lazy = true
hooks_file = '~/vimfiles/plug/conf/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'
depends = 'denops.vim'
# denops_shared_server# だと denops_shared_server#install() などの実行に失敗する。
on_func = [
  'denops_shared_server#install',
  'denops_shared_server#restart',
  'denops_shared_server#uninstall',
]

# [[plugins]]
# repo = 'vim-denops/denops-startup-recorder.vim'
# on_source = 'denops.vim'
