[[plugins]]
repo = 'Shougo/ddu.vim'
lazy = true
on_func = 'ddu#'
depends = 'denops.vim'
hooks_file = '~/vimfiles/rc/dein/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-filter-sorter_mtime'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_reversed'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'hokorobi/ddu-source-git_log'
extAttrs = { installerFrozen = true }
on_source = 'ddu.vim'
depends = 'vim-gin'

[[plugins]]
repo = 'kyoh86/ddu-source-git_branch'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-git_diff_tree'
on_source = 'ddu.vim'

[[plugins]]
repo = 'peacock0803sz/ddu-source-git_stash'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-output'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-quickfix_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'nekowasabi/ddu-source-vim-bookmark'
depends = 'vim-bookmarks'
on_source = 'ddu.vim'

[[plugins]]
repo = '4513ECHO/ddu-source-source'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-zenn_dev'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'
