[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-packspec'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
