[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-packspec'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[multiple_hooks]]
plugins = ['ddu.vim', 'dpp.vim']
hook_add = '''
  nnoremap <silent> <Space>du <Cmd>call ddu#start(#{sources: [#{name: 'dpp', params: #{names: dpp#sync_ext_action('installer', 'getNotUpdated')->map({_, val -> val.name}), },}]})<CR>
'''
