hooks_file = '~/vimfiles/rc/dein/ft.vim'
# memo
# on_source = このプラグインがリストのプラグインより先に読み込まれる
# depends = リストのプラグインがこのプラグインより先に読み込まれる
# on_cmd = 自分で定義したコマンドは登録しない。一度実行したら消えるみたい。

# Plugin Manager {{{1
[[plugins]]
repo = 'hokorobi/vim-templug'
frozen = true
on_cmd = 'Templug'
hook_add = 'set packpath+=~/_vim'

# }}}1  LSP {{{1
# 遅延読込を実現しようとすると色々と大変。
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hooks_file = '~/vimfiles/rc/dein/lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hooks_file = '~/vimfiles/rc/dein/lsp-settings.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = 'denops.vim'
on_func = 'signature_help#'
hooks_file = '~/vimfiles/rc/dein/denops-signature_help.vim'
# }}}1  REPL {{{1

# Quickrun {{{2

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = 'shabadou.vim'
hooks_file = '~/vimfiles/rc/dein/quickrun.vim'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# }}}2

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']

# }}}1  Text Object {{{1

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'mattn/vim-textobj-url'
depends = 'vim-textobj-user'
on_map = {ox = ['iu', 'au']}

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'ModeChanged'
hooks_file = '~/vimfiles/rc/dein/sandwich.vim'

[[plugins]]
repo = 'tommcdo/vim-exchange'
on_map = {n = 'cx', x = 'X'}

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
on_map = {ox = ['ii', 'ai', 'iI']}

[[plugins]]
repo = 'glts/vim-textobj-comment'
on_map = {ox = ['ac', 'aC', 'ic']}
depends = 'vim-textobj-user'

[[plugins]]
repo = 'romgrk/equal.operator'
on_map = {ox = ['<Plug>(operator-', '<Plug>(visual-']}
hooks_file = '~/vimfiles/rc/dein/equal.operator.vim'

[[plugins]]
repo = 'machakann/vim-textobj-functioncall'
on_map = {ox = ['<Plug>']}
on_source = 'vim-sandwich'
hooks_file = '~/vimfiles/rc/dein/textobj-functioncall.vim'

[[plugins]]
repo = 'machakann/vim-textobj-delimited'
on_map = {ox = ['ad', 'aD', 'id', 'iD']}

[[plugins]]
repo = 'kana/vim-textobj-line'
on_map = {ox = ['al', 'il']}
hooks_file = '~/vimfiles/rc/dein/textobj-line.vim'

# }}}1  Language, Format, Filetype {{{1

# diff {{{2

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'
hooks_file = '~/vimfiles/rc/dein/linediff.vim'

# }}}2 Python {{{2

[[plugins]]
repo = 'hdima/python-syntax'
hooks_file = '~/vimfiles/rc/dein/python-syntax.vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# }}}2 Golang {{{2

[[plugins]]
repo = 'mattn/vim-godoc'

[[plugins]]
repo = 'mattn/vim-gorun'

[[plugins]]
repo = 'mattn/vim-goaddtags'

# }}}2 Markdown {{{2

[[plugins]]
repo = 'previm/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hooks_file = '~/vimfiles/rc/dein/markdown.vim'

# }}}2 rst {{{2

[[plugins]]
repo = 'hokorobi/vim-rst-util'
frozen = true
on_ft = 'rst'
hooks_file = '~/vimfiles/rc/dein/rst-util.vim'

[[plugins]]
repo = 'habamax/vim-rst'
on_ft = 'rst'

# }}}2 quickfix {{{2

[[plugins]]
repo = 'lambdalisue/qfloc.vim'
on_ft = 'qf'
hooks_file = '~/vimfiles/rc/dein/qfloc.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

# preview Quickfix at popup
# [[plugins]]
repo = 'AndrewRadev/quickpeek.vim'
#   on_ft = 'qf'
#   hooks_file = '~/vimfiles/rc/dein/quickpeek.vim'
# 
# preview Quickfix at popup
[[plugins]]
repo = 'bfrg/vim-qf-preview'
on_ft = 'qf'
hooks_file = '~/vimfiles/rc/dein/qf-preview.vim'

[[plugins]]
repo = 'mattn/vim-qfnavigate'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/qfnavigate.vim'

# QuickFixでジャンプするときに直前のWindowを使う
[[plugins]]
repo = 'yssl/QFEnter'
on_ft = 'qf'

[[plugins]]
repo = 'bfrg/vim-qf-history'
on_cmd = ['Chistory', 'Lhistory']
hooks_file = '~/vimfiles/rc/dein/qf-history.vim'

# }}}2 Vim {{{2

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

# Vim script の最後に発生したエラーの箇所を開く
[[plugins]]
repo = 'rbtnn/vim-vimscript_lasterror'
on_cmd = 'VimscriptLastError'

[[plugins]]
repo = 'rbtnn/vim-vimscript_tagfunc'
on_ft = 'vim'

[[plugins]]
repo = 'rbtnn/vim-vimscript_indentexpr'
on_ft = 'vim'

# }}}2 Others {{{2

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
depends = 'open-browser.vim'
on_cmd = 'PlantumlOpen'
hooks_file = '~/vimfiles/rc/dein/plantuml-previewer.vim'

[[plugins]]
repo = 'hokorobi/plantuml-syntax'
# rev = 'dev'
frozen = true
merged = false

[[plugins]]
repo = 'hnamikaw/vim-autohotkey'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_cmd = 'RainbowDelim'

[[plugins]]
repo = 'hokorobi/vim-howm-syntax-mini'
frozen = true

#}}}2

# }}}1  Look {{{1

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hooks_file = '~/vimfiles/rc/dein/color-spring-night.vim'

# インクリメンタルサーチの件数をポップアップ表示
[[plugins]]
repo = 'obcat/vim-hitspop'
on_event = 'CmdlineEnter'
hooks_file = '~/vimfiles/rc/dein/hitspop.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-color-spring-night'
hooks_file = '~/vimfiles/rc/dein/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-cursorword'

# replace matchparen
[[plugins]]
repo = 'andymass/vim-matchup'
hooks_file = '~/vimfiles/rc/dein/matchup.vim'

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/quickhl.vim'

# :substitute などで変更対象のハイライト、変更後のプレビュー
[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdlineEnter'
hooks_file = '~/vimfiles/rc/dein/traces.vim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = 'Vista'
hooks_file = '~/vimfiles/rc/dein/vista.vim'

[[plugins]]
repo = 'lambdalisue/readablefold.vim'

# #rrggbb や #rgb の色を視覚化
[[plugins]]
repo = 'BourgeoisBear/clrzr'
on_cmd = 'ClrzrOn'
hooks_file = '~/vimfiles/rc/dein/clrzr.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hooks_file = '~/vimfiles/rc/dein/highlightedyank.vim'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'
hooks_file = '~/vimfiles/rc/dein/ambiwidth.vim'

[[plugins]]
repo = 'wellle/context.vim'
on_cmd = 'ContextActivate'
hooks_file = '~/vimfiles/rc/dein/context.vim'

# }}}1  Input & Edit {{{1

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = '~/vimfiles/rc/dein/lexima.vim'

# https://scrapbox.io/vim-jp/lexima.vim%E3%81%A7Better_vim-altercmd%E3%82%92%E5%86%8D%E7%8F%BE%E3%81%99%E3%82%8B
[[plugins]]
repo = 'yuki-yano/lexima-alter-command.vim'
on_event = ['CmdlineEnter']
depends = 'lexima.vim'
hooks_file = '~/vimfiles/rc/dein/lexima-alter-command.vim'

[[plugins]]
repo = 'thinca/vim-ambicmd'
on_event = ['CmdlineEnter']
depends = 'lexima.vim'
hooks_file = '~/vimfiles/rc/dein/ambicmd.vim'

[[plugins]]
repo = 'uplus/vim-clurin'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/clurin.vim'

[[plugins]]
repo = 'kg8m/vim-simple-align'
on_cmd = 'SimpleAlign'
rev = 'vim9'

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'
hooks_file = '~/vimfiles/rc/dein/undotree.vim'

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/jplus.vim'

[[plugins]]
repo = 'hokorobi/yankround.vim'
on_cmd = 'CtrlPYankRound'
hooks_file = '~/vimfiles/rc/dein/yankround.vim'

# g<C-a> などは同行での連番はできないようなので、まだ有用
[[plugins]]
repo = 'deris/vim-rengbang'
on_cmd = ['RengBang', 'RengBangUsePrev', 'RengBangConfirm']
hooks_file = '~/vimfiles/rc/dein/rengbang.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
on_cmd = ['StripWhitespace', 'ToggleStripWhitespaceOnSave']
hooks_file = '~/vimfiles/rc/dein/better-whitespace.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = 'Template'
on_map = {ni = '<C-y>'}
hooks_file = '~/vimfiles/rc/dein/sonictemplate.vim'

[[plugins]]
repo = 'deris/vim-pasta'
on_map = {nx = ['<Space>p', '<Space>P']}
hooks_file = '~/vimfiles/rc/dein/pasta.vim'

[[plugins]]
repo = 'nocd5/ExpandSerialNumber.vim'
on_cmd = 'ExpandSerialNumber'

[[plugins]]
repo = 'lambdalisue/vim-findent'
on_cmd = ['Findent', 'FindentRestore']
hooks_file = '~/vimfiles/rc/dein/findent.vim'

[[plugins]]
repo = 'machakann/vim-swap'
on_map = {ox = ['<Plug>'], n = ['gs', 'g<', 'g>']}
hooks_file = '~/vimfiles/rc/dein/swap.vim'

# 選択した行すべてに対して I, A を反映させる。
[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = ['I', 'gI', 'A']}

[[plugins]]
repo = 'tyru/caw.vim'
depends = 'vim-repeat'
on_map = '<Plug>(caw:prefix)'
hooks_file = '~/vimfiles/rc/dein/caw.vim'

[[plugins]]
repo = 'kana/vim-repeat'
lazy = true

[[plugins]]
repo = 'matze/vim-move'
on_map = '<Plug>Move'
hooks_file = '~/vimfiles/rc/dein/move.vim'

[[plugins]]
repo = 'sentriz/vim-print-debug'
on_func = 'print_debug#print_debug'
hooks_file = '~/vimfiles/rc/dein/print-debug.vim'

# }}}1  Motion {{{1

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {nxo = '<Plug>'}
hooks_file = '~/vimfiles/rc/dein/easymotion.vim'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/edgemotion.vim'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>'
hooks_file = '~/vimfiles/rc/dein/asterisk.vim'

[[plugins]]
repo = 'hrsh7th/vim-searchx'
on_func = 'searchx#run'
hooks_file = '~/vimfiles/rc/dein/searchx.vim'

# カーソル移動位置を遡る
[[plugins]]
repo = 'osyo-manga/vim-milfeulle'
hooks_file = '~/vimfiles/rc/dein/milfeulle.vim'

[[plugins]]
repo = 'hokorobi/vim-smarthome'
frozen = true
hooks_file = '~/vimfiles/rc/dein/smarthome.vim'

[[plugins]]
repo = 'osyo-manga/vim-operator-stay-cursor'
depends = 'vim-operator-user'
on_func = 'operator#stay_cursor#wrapper'
hooks_file = '~/vimfiles/rc/dein/operator-stay-cursor.vim'

# 遅延読み込みだと前回起動時のマークが復元されない様子
[[plugins]]
repo = 'hokorobi/vim-bookmarks'
#rev = 'hokorobi'
frozen = true
hooks_file = '~/vimfiles/rc/dein/bookmarks.vim'

[[plugins]]
repo = 'Allianaab2m/jumpout.vim'
on_func = 'jumpout#'
hooks_file = '~/vimfiles/rc/dein/jumpout.vim'

# }}}1  Buffer {{{1

[[plugins]]
repo = 'hokorobi/vim-sayonara'
on_func = 'sayonara#'
frozen = true
hooks_file = '~/vimfiles/rc/dein/sayonara.vim'

[[plugins]]
repo = 'tyru/closesubwin.vim'
on_func = 'closesubwin#'
hooks_file = '~/vimfiles/rc/dein/closesubwin.vim'

[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'
hooks_file = '~/vimfiles/rc/dein/capture.vim'

# }}}1  File {{{1

[[plugins]]
repo = 'kana/vim-gf-user'
on_map = {n = 'gf'}
hooks_file = '~/vimfiles/rc/dein/gf-user.vim'

# diff でも gf を可能にする
[[plugins]]
repo = 'kana/vim-gf-diff'
on_ft = 'diff'
depends = 'vim-gf-user'

# FIXME: 遅延読込設定をしている場合、起動後の初回実行時にファイルの内容が二重に表示される
#        ファイル末尾にファイルの先頭からの内容が表示される。本当に先頭からではなく2行目からの様子
#        sample: :e https://raw.githubusercontent.com/Mathiasb17/mathias/f3ad028eafcc56ddd4d72019cb6a1818e456d099/.config/nvim/init.vim
[[plugins]]
repo = 'lambdalisue/vim-protocol'

[[plugins]]
repo = 'mattn/vim-findroot'
on_event = 'BufRead'
hooks_file = '~/vimfiles/rc/dein/findroot.vim'

[[plugins]]
repo = 'chrisbra/Recover.vim'

# }}}1  Terminal {{{1
# terminal 上で、未入力時に ESC, : が効くようにする
[[plugins]]
repo = 'tyru/empty-prompt.vim'
on_event = 'TerminalOpen'
hooks_file = '~/vimfiles/rc/dein/empty-prompt.vim'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = 'FloatermNew'
on_func = 'floaterm#'
hooks_file = '~/vimfiles/rc/dein/floaterm.vim'

# }}}1  CtrlP {{{1
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hooks_file = '~/vimfiles/rc/dein/ctrlp.vim'

[[plugins]]
repo = 'hokorobi/ctrlp-sessions'
on_cmd = ['CtrlPSession', 'MkS']
hooks_file = '~/vimfiles/rc/dein/ctrlp-sessions.vim'

[[plugins]]
repo = 'mattn/ctrlp-launcher'
on_cmd = 'CtrlPLauncher'
hooks_file = '~/vimfiles/rc/dein/ctrlp-launcher.vim'

[[plugins]]
repo = 'printesoi/ctrlp-filetype.vim'
on_cmd = 'CtrlPFiletype'
hooks_file = '~/vimfiles/rc/dein/ctrlp-filetype.vim'

[[plugins]]
repo = 'christoomey/ctrlp-generic'
on_func = 'CtrlPGeneric'
hooks_file = '~/vimfiles/rc/dein/ctrlp-generic.vim'

[[plugins]]
repo = 'suy/vim-ctrlp-commandline'
hooks_file = '~/vimfiles/rc/dein/ctrlp-commandline.vim'

[[plugins]]
repo = 'hokorobi/ctrlp-grep'
on_cmd = 'CtrlPGrep'
hooks_file = '~/vimfiles/rc/dein/ctrlp-grep.vim'

[[plugins]]
repo = 'mattn/ctrlp-matchfuzzy'
hooks_file = '~/vimfiles/rc/dein/ctrlp-matchfuzzy.vim'

[[plugins]]
repo = 'ompugao/ctrlp-kensaku'
depends = ['denops.vim', 'kensaku.vim']
on_cmd = ['CtrlPKensaku', 'ToggleCtrlPKensaku']
hooks_file = '~/vimfiles/rc/dein/ctrlp-kensaku.vim'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
lazy = true

# }}}1  Git {{{1
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hooks_file = '~/vimfiles/rc/dein/gina.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'
on_cmd = ['Gin', 'GinBranch', 'GinBrowse', 'GinBuffer', 'GinChaperon', 'GinDiff', 'GinEdit', 'GinLog', 'GinPatch', 'GinStatus']
depends = 'denops.vim'
hooks_file = '~/vimfiles/rc/dein/gin.vim'

[[plugins]]
repo = 'cohama/agit.vim'
on_cmd = 'Agit'
hooks_file = '~/vimfiles/rc/dein/agit.vim'

[[plugins]]
repo = 'hotwatermorning/auto-git-diff'
on_ft = 'gitrebase'

# GitHub {{{2
[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
on_map = '<Plug>'
depends = 'open-browser.vim'
hooks_file = '~/vimfiles/rc/dein/gista.vim'

# }}}2
# }}}1 Utility {{{1
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-'
on_func = 'openbrowser#open'
hooks_file = '~/vimfiles/rc/dein/open-browser.vim'

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = 'PP'
hooks_file = '~/vimfiles/rc/dein/prettyprint.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'skanehira/code2img.vim'
on_cmd = 'Code2img'

[[plugins]]
repo = 'fedorenchik/VimCalc3'
on_cmd = 'Calc'
hooks_file = '~/vimfiles/rc/dein/calc3.vim'

[[plugins]]
repo = 'kana/vim-submode'
on_source = ['vim-lsp', 'yankround.vim', 'vim-easymotion']
hooks_file = '~/vimfiles/rc/dein/submode.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'
hooks_file = '~/vimfiles/rc/dein/helpful.vim'

[[plugins]]
repo = 'rbtnn/vim-layout'
depends = 'ctrlp-generic'
on_func = ['layout#', 'LayoutWrap', 'LayoutCallback']
on_cmd = ['LayoutLoad', 'LayoutSave']
hooks_file = '~/vimfiles/rc/dein/layout.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
lazy = true
hooks_file = '~/vimfiles/rc/dein/denops.vim'
# }}}1
